services:
  mdb-to-postgresql:
    build: .
    container_name: mdb-to-postgresql
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=UTC
